<?php
/**
 * @file
 * hot_tables.module
 */




/**
 * Implementation of hook_entity_info_alter()
 */
function hot_asides_entity_info_alter(&$entity_info){
  // Basic table
  $entity_info['fieldable_panels_pane']['bundles']['hot_asides'] = array(
    'label' => t('Aside'),
    'pane category' => t('HotWidgets!'),
    'pane top level' => FALSE,
    'pane icon' => HOT_BUTTONS_PATH . '/images/icon_button.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-asides',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}



/**
 * Implements hook_theme()
 */

 function hot_asides_theme($existing, $type, $theme, $path){
   return array(
     'field__field_basic_url__hot_asides' => array(
        'function' => 'theme_field__field_basic_url__hot_asides'
     )
   );
 }
 /**
  * Theme callback for the field
  */
 function theme_field__field_basic_url__hot_asides(&$variables){
   $output = '';


  // Render the items.
  $output .= '<nav class="list-group" role="navigation"' . $variables['content_attributes'] . '>';
  $path = current_path();
  $path = $GLOBALS['base_url'] . '/' . drupal_get_path_alias($path);

  foreach ($variables['items'] as $delta => $item) {
    $active = $path == $item['#element']['url'] ? ' active' : '';
    $item['#element']['attributes'] = array(
      'class' => 'list-group-item' . $active,
    );
    $output .= drupal_render($item);
  }
  $output .= '</nav>';

  // Render the top-level DIV.
  $output = '<div class="' . $variables['classes'] . '"' . $variables['attributes'] . '>' . $output . '</div>';

  return $output;

 }
